server_connect_timeout: 5000
enforce_secure_profile: false
remote_ping_cache: -1
forge_support: true
player_limit: 100
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - bungeecord.command.kick
timeout: 30000
log_commands: false
network_compression_threshold: 256
online_mode: true
disabled_commands:
- reload
servers:
  lobby:
    motd: "&c&lRed&7&lCraft&f.org - Lobby"
    address: localhost:25566
    restricted: false
  crea_build_plot:
    motd: "&c&lRed&7&lCraft&f.org - Crea Build Plot"
    address: localhost:25567
    restricted: false
  crea_redstone_plot:
    motd: "&c&lRed&7&lCraft&f.org - Crea Redstone Plot"
    address: localhost:25568
    restricted: false
listeners:
- query_port: 25565
  motd: "&c&lRed&7&lCraft&f.org"
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    lobby.redcraft.org: lobby
    buildplot.redcraft.org: crea_build_plot
    redplot.redcraft.org: crea_redstone_plot
  ping_passthrough: false
  priorities:
  - lobby
  - crea_build_plot
  - crea_redstone_plot
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 1
  tab_size: 60
  force_default_server: false
ip_forward: true
remote_ping_timeout: 5000
prevent_proxy_connections: false
groups:
  lululombard:
  - admin
connection_throttle: 4000
stats: db28d717-89ab-4fab-af2c-84aee259b760
connection_throttle_limit: 3
log_pings: true
